---

- name: Include OS specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- name: Include RedHat specific plays
  include: install-{{ ansible_os_family }}.yml
  when: ansible_os_family == "RedHat"

- name: Include Debian specific plays
  include: install-{{ ansible_os_family }}.yml
  when: ansible_os_family == "Debian"

- name: Remove defaults
  include: remove-defaults.yml

- name: Nginx configuration
  include: config.yml
